export const Pokeinfo = [
  {
    id: "#001",
    name: "Bulbasaur",
    img: "Images/bulbasaur.png",
    primaryColor: "#74CB48",
    secondaryColor: "#A43E9E",
    type: ["Grass", "Poison"],
    weight: "6.9 kg",
    height: "0.7 m",
    moves: "Chlorophyll Overgrow",
    description:
      "There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger.",
    hp: "045",
    atk: "049",
    det: "049",
    satk: "065",
    sdef: "065",
    spd: "045",
  },
  {
    id: "#012",
    name: "Butterfree",
    img: "Images/butterfree.png",
    primaryColor: "#A7B723",
    secondaryColor: "#A891EC",
    type: ["Bug", "Flying"],
    weight: "32.0Kg",
    height: "1.1 m",
    moves: "Compound-Eyes, Tinted-Lens",
    description:
      "In battle, it flaps its wings at great speed to release highly toxic dust into the air",
    hp: "060",
    atk: "045",
    def: "050",
    satk: "090",
    sdef: "080",
    spd: "070",
  },
  {
    id: "#004",
    name: "Charmander",
    img: "Images/charmander.png",
    primaryColor: "#F57D31",
    secondaryColor: "",
    type: ["Fire"],
    weight: "8.5Kg",
    height: "0.6 m",
    moves: "Mega-Punch Fire-Punch",
    description:
      "It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail",
    hp: "039",
    atk: "052",
    def: "043",
    satk: "060",
    sdef: "050",
    spd: "065",
  },
  {
    id: "#007",
    name: "Squirtle",
    img: "Images/squirtle.png",
    primaryColor: "#6493EB",
    secondaryColor: "",
    type: ["Water"],
    weight: "9.0Kg",
    height: "0.5 m",
    moves: "Torrent Rain-Dish",
    description:
      "When it retracts its long neck into its shell, it squirts out water with vigorous force",
    hp: "044",
    atk: "048",
    def: "065",
    satk: "050",
    sdef: "064",
    spd: "043",
  },
  {
    id: "#132",
    name: "Ditto",
    img: "Images/ditto.png",
    primaryColor: "#AAA67F",
    secondaryColor: "",
    type: ["Normal"],
    weight: "4.0Kg",
    height: "0.3 m",
    moves: "Limber Imposter",
    description:
      "It can reconstitute its entire cellular structure to change into what it sees, but it returns to normal when it relaxes",
    hp: "048",
    atk: "048",
    def: "048",
    satk: "048",
    sdef: "048",
    spd: "048",
  },
  {
    id: "#132",
    name: "Aron",
    img: "Images/aron.png",
    primaryColor: "#B7B9D0",
    secondaryColor: "#B69E31",
    type: ["Steel", "Rock"],
    weight: "60.0Kg",
    height: "0.4 m",
    moves: "Sturdy Rock-Head",
    description:
      "It eats iron ore - and sometimes railroad tracks - to build up the steel armor that protects its body",
    hp: "050",
    atk: "070",
    def: "100",
    satk: "040",
    sdef: "040",
    spd: "030",
  },
  {
    id: "#092",
    name: "Gastly",
    img: "Images/gastly.png",
    primaryColor: "#70559B",
    secondaryColor: "",
    type: "Ghost",
    weight: "0.1Kg",
    height: "1.3 m",
    moves: "Levitate",
    description:
      "Born from gases, anyone would faint if engulted by its gaseous body, which contains poison",
    hp: "030",
    atk: "035",
    def: "030",
    satk: "100",
    sdef: "035",
    spd: "080",
  },
  {
    id: "#152",
    name: "Mew",
    img: "Images/mew.png",
    primaryColor: "#FB5584",
    secondaryColor: "",
    type: "Phychic",
    weight: "4.0Kg",
    height: "0.4 m",
    moves: "Synchronize",
    description:
      "When viewed through a microscope, this Pokemons short, fine, delicate hair can be seen",
    hp: "030",
    atk: "035",
    def: "030",
    satk: "100",
    sdef: "035",
    spd: "080",
  },
  {
    id: "#025",
    name: "Pikachu",
    img: "Images/pikachu.png",
    primaryColor: "#F9CF30",
    secondaryColor: "",
    type: "Electric",
    weight: "6.0Kg",
    height: "0.4 m",
    moves: "Pay-Day Mega-Punch",
    description:
      "Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy",
    hp: "035",
    atk: "055",
    def: "040",
    satk: "050",
    sdef: "050",
    spd: "090",
  },
];
