export const Pokeinfo = {
  pokemon1: {
    id: "#001",
    name: "Bulbasaur",
    img: "Images/bulbasaur.png",
    primaryColor: "#74CB48",
    secondaryColor: "#A43E9E",
    type: ["Grass", "Poison"],
    weight: "6.9 kg",
    height: "0.7 m",
    moves: "Chlorophyll Overgrow",
    description:
      "There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger.",
    hp: "045",
    atk: "049",
    det: "049",
    satk: "065",
    sdef: "065",
    spd: "045",
  },
  pokemon6: {
    id: "#092",
    name: "Gastly",
    img: "Images/gastly.png",
    primaryColor: "#70559B",
    secondaryColor: "#666666",
    type: ["Ghost", "Type"],
    weight: "0.1 kg",
    height: "1.3 m",
    moves: "Levitate",
    description:
      "Born from gases, anyone would faint if engulfed by its gaseous body, which contains poison.",
    hp: "030",
    atk: "035",
    det: "030",
    satk: "100",
    sdef: "035",
    spd: "080",
  },
  pokemon7: {
    id: "#132",
    name: "Ditto",
    img: "Images/ditto.png",
    primaryColor: "#AAA67F",
    secondaryColor: "",
    type: ["Normal"],
    weight: "4.0 kg",
    height: "0.3 m",
    moves: "Limber Imposter",
    description:
      "It can reconstitute its entire cellular structure to change into what it sees, but it returns to normal when it relaxes.",
    hp: "048",
    atk: "048",
    det: "048",
    satk: "048",
    sdef: "048",
    spd: "048",
  },
  pokemon8: {
    id: "#152",
    name: "Mew",
    img: "Images/mew.png",
    primaryColor: "#FB5584",
    secondaryColor: "",
    type: ["Psychic"],
    weight: "4.0 kg",
    height: "0.4 m",
    moves: "Synchronize",
    description:
      "When viewed through a microscope, this Pokémon's short line, delicate hair can be seen.",
    hp: "100",
    atk: "100",
    det: "100",
    satk: "100",
    sdef: "100",
    spd: "100",
  },
  pokemon9: {
    id: "#304",
    name: "Aron",
    img: "Images/aron.png",
    primaryColor: "#B7B9D0",
    secondaryColor: "#B69E31",
    type: ["Steel", "Rock"],
    weight: "60.0 kg",
    height: "0.4 m",
    moves: "Sturdy Rock-Head",
    description:
      "It eats iron ore - and sometimes railroad tracks - to build up the steel armor that protects its body.",
    hp: "050",
    atk: "070",
    det: "100",
    satk: "040",
    sdef: "040",
    spd: "030",
  },
};
